---
apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdEnvironment
metadata:
  name: dev-env
spec:
  targetNamespace: topo-sources
  providers:
    web:
      port: 8000
      mode: operator
    metrics:
      port: 9000
      mode: operator
      path: "/metrics"
    kafka:
      namespace: topo-sources
      clusterName: crc.testing
      mode: local
    db:
      image: "registry.redhat.io/rhel8/postgresql-12:1-36"
      mode: local
    logging:
      mode: none
    objectStore:
      mode: none
    inMemoryDb:
      mode: none
  resourceDefaults:
    limits: 
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "384Mi"

